# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('pos', models.CharField(max_length=5)),
                ('salary', models.FloatField(default=0)),
                ('points', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default=None, max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('pos', models.CharField(default=None, max_length=5)),
                ('games', models.IntegerField(default=0)),
                ('plays', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('avg_salary', models.IntegerField(default=0)),
                ('avg_points_game', models.IntegerField(default=0)),
                ('avg_points_away', models.IntegerField(default=0)),
                ('avg_points_home', models.IntegerField(default=0)),
                ('deviation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('o_points', models.IntegerField(default=0)),
                ('d_points', models.IntegerField(default=0)),
                ('o_points_away', models.IntegerField(default=0)),
                ('o_points_home', models.IntegerField(default=0)),
                ('d_points_away', models.IntegerField(default=0)),
                ('d_points_home', models.IntegerField(default=0)),
                ('a_deviation', models.IntegerField(default=0)),
                ('h_deviation', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('team', 'name', 'pos')]),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='Away',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='OpposingTeam', to='stats.Team'),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='Home',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Team'),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='Player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Player'),
        ),
    ]
