# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('games', models.IntegerField(default=0)),
                ('plays', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('avg_salary', models.IntegerField(default=0)),
                ('avg_points_game', models.IntegerField(default=0)),
                ('avg_points_away', models.IntegerField(default=0)),
                ('avg_points_home', models.IntegerField(default=0)),
                ('deviation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
                ('o_points', models.IntegerField(default=0)),
                ('d_points', models.IntegerField(default=0)),
                ('o_points_away', models.IntegerField(default=0)),
                ('o_points_home', models.IntegerField(default=0)),
                ('d_points_away', models.IntegerField(default=0)),
                ('d_points_home', models.IntegerField(default=0)),
                ('a_deviation', models.IntegerField(default=0)),
                ('h_deviation', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='h_a',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='oppt',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='team',
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='Away',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='OpposingTeam', to='stats.Team'),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='Home',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Team'),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='Player',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Player'),
        ),
    ]
