# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='deviation',
        ),
        migrations.RemoveField(
            model_name='player',
            name='plays',
        ),
        migrations.RemoveField(
            model_name='team',
            name='a_deviation',
        ),
        migrations.RemoveField(
            model_name='team',
            name='h_deviation',
        ),
        migrations.AddField(
            model_name='player',
            name='avg_salary_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_salary_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='games_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='games_home',
            field=models.IntegerField(default=0),
        ),
    ]
