# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20171207_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestats',
            name='Away',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='OpposingTeam', to='stats.Team'),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='Home',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Team'),
        ),
    ]
