# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20171208_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='salary_total',
            field=models.IntegerField(default=0),
        ),
    ]
