# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_player_salary_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='salary_total_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='salary_total_home',
            field=models.IntegerField(default=0),
        ),
    ]
